export default function DisclaimerBanner() {
  return (
    <div className="bg-brand-yellow/10 border border-brand-yellow/40 rounded-lg px-4 py-2.5 flex items-start gap-2.5 print:hidden">
      <span className="text-brand-yellow font-bold text-sm mt-px flex-shrink-0">!</span>
      <p className="text-xs text-gray-700 leading-relaxed">
        <strong className="font-semibold">Draft document only.</strong> Documents generated by Prelegal are provided as a starting point and have not been reviewed by an attorney. They should not be relied upon as legal advice. Please have a qualified legal professional review any agreement before signing.
      </p>
    </div>
  )
}
